### ISSUE TITLE
error: patch failed

### ISSUE THREAD

**Issue by fififei** [aws-samples/cvat-on-aws-china#1]
`git apply ../aws-cvat.patch` failed, can not modify CVAT server.
Does anyone have the same problem with me?
looking forward for some advice, thx!
--------
error: patch failed: cvat/requirements/base.txt:5
error: cvat/requirements/base.txt: patch does not apply
error: patch failed: cvat/settings/production.py:33
error: cvat/settings/production.py: patch does not apply
error: patch failed: supervisord.conf:17
error: supervisord.conf: patch does not apply

**Comment by zorrofox** [comment]
You must first run all these commands:
```
cd ..
git clone https://github.com/openvinotoolkit/cvat.git
cd cvat
git checkout c48411ae5014aac4441aa03da8944fbd4373b312
git apply ../aws-cvat.patch
```

And your error is missing the original CVAT repository.
