### ISSUE TITLE
Permission change?

### ISSUE THREAD

**Issue by masatoUmemoto** [aws-samples/cvat-on-aws-china#3]
Thank you for introducing good AWS usage

I tried it, but I can't deploy CloudFormation.

I get the following error

Please help me

![image](https://user-images.githubusercontent.com/76215058/150470868-5ffa2901-0e16-4bf1-a9c2-ec0800957bcb.png)

	Failed to download model data for container "container_1" from URL: "s3://sagemaker-ap-northeast-1-cvat/cvat/pth-inside-outside-guidance/model.tar.gz". Please ensure that there is an object located at the URL and that the role passed to CreateModel has permissions to download the object.

**Comment by fififei** [comment]
Thank you for your comment.
I think I have fixed the problem.
Cloud you try it one more time?

Or, you can deploy CFn by clicking the 「Launch Stack」icon in this blog(https://aws.amazon.com/jp/blogs/news/use-amazon-sagemaker-to-deploy-cvat-ai-automatic-image-annotation-system/).
![image](https://user-images.githubusercontent.com/40173816/150728025-8179a65e-47d3-4473-ae52-2c8b56a6a1ef.png)
